### PR TITLE
Bugfix: kubelet on edge node keeps restarting issue

### LINKED ISSUE #367: [BUG] Edgenode Turns to NotReady, kubelet on It Restart Rapidly
**What happened**:

After executing `_output/local/bin/linux/amd64/yurtctl convert --provider kubeadm --cloud-nodes master` on master node of an established Kubernetes cluster of two nodes, all pods are pulled and started as expected, but the status of the edge node turns to `NotReady`. Check kubelet's log with `journalctl -xeu kubelet` on that device, we can see kubelet keep restart every few minutes.  

**What you expected to happen**:

After conversion, edge node rejoins the cluster, and has it status `Ready`. 

**How to reproduce it (as minimally and precisely as possible)**: (updated due to further investigation)

- Setup a Kubernetes cluster (I did it with kubeadm) 
- Execute `_output/local/bin/linux/amd64/yurtctl convert --provider kubeadm --cloud-nodes master` on master node (called master)
- Reset yurt with `_output/local/bin/linux/amd64/yurtctl convert`
- Reset the cluster (with `kubeadm reset`)
- Setup the Kubernetes cluster again with new credential
- Execute `yurtctl convert` again
- Issue happens

**Anything else we need to know?**:

- If I do the conversion manually following https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/manually-setup.md, everything is fine.
- `/etc/kubernetes/manifests/yurt-hub.yaml` created by `openyurt/yurtctl-servant` is different from what created in this way: https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/manually-setup.md#setup-yurthub
- If I replace `yurt-hub.yaml` with the file used in a manually-setup, the system recovers from the issue.

**Environment**:
- OpenYurt version: V0.4.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g: `cat /etc/os-release`):  
Cloud node:  
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Edge node:  
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Kernel (e.g. `uname -a`):  
Cloud node:  
```
Linux node-3 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Edge node:  
```
Linux ubuntu 5.4.0-1036-raspi #39-Ubuntu SMP PREEMPT Wed May 12 17:37:51 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

- Install tools: kubeadm
- Others:

**others**
https://github.com/openyurtio/openyurt/issues/360#issuecomment-865690544

/kind bug

### PR DESCRIPTION
**Pull request by Windrow**
Bugfix: kubelet on edge node keeps restarting after yurtctl convert executed issue. 

With current configuration, `/var/lib/yurthub` is used but not cleared on reset, and files in it would not be updated on next setup. Therefore, if we reuse the reset edge node again when credential of the cluster changed, kubehub would use wrong credential after conversion. 

`yurthub.yaml` in `yaml-template` uses `/etc/kubernetes/pki` instead of `/var/lib/yurthub`, which could be a replacement. 

See detailed description and investigation process of the issue at https://github.com/openyurtio/openyurt/issues/367.

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #367 

#### Special notes for your reviewer:

/assign @rambohe-ch @yixingjia 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/yurtctl/util/edgenode/common.go [hunk 1]
```diff
@@ -60,29 +60,34 @@ metadata:
...
+    - name: pki
+      mountPath: /etc/kubernetes/pki
+    - name: pem-dir
+      mountPath: /var/lib/kubelet/pki
     command:
     - yurthub
     - --v=2
     - --server-addr=__kubernetes_service_addr__
     - --node-name=$(NODE_NAME)
-    - --join-token=__join_token__
```
Comment (Peeknut) [inline pkg/yurtctl/util/edgenode/common.go:85]: Why delete parameter `--join-token` which generated when converted by yurtctl.

**Review by qclc — COMMENTED** [review]
The current solution seems to be the ca and key of the kubelet used by default, so it seems that there is no difference between hubself and kubelet mode by default.

File: pkg/yurtctl/util/edgenode/common.go (hunk 1 above)
Comment (Windrow) [reply pkg/yurtctl/util/edgenode/common.go:85]: `join-token` is not specified in `openyurt/config/yaml-templateyurthub.yaml`. I think it is not a must if we do not use hubself mode.

**Comment by Windrow** [comment]
> The current solution seems to be the ca and key of the kubelet used by default, so it seems that there is no difference between hubself and kubelet mode by default.

`openyurt/cmd/yurthub/app/options/options.go` line 67. Default `CertMgrMode` is `hubself` there. 

> https://github.com/openyurtio/openyurt/pull/370#discussion_r659482370

But if we do not provide `join-token`, it will use kubelet method instead. They do have different implementations in fact.

**Comment by Windrow** [comment]
Working on a solution to the root cause.

/do not merge

File: pkg/yurtctl/util/edgenode/common.go [hunk 2]
```diff
@@ -60,29 +60,34 @@ metadata:
   namespace: kube-system
 spec:
   volumes:
-  - name: hub-dir
+  - name: pki
     hostPath:
-      path: /var/lib/yurthub
-      type: DirectoryOrCreate
+      path: /etc/kubernetes/pki
+      type: Directory
```
Comment (rambohe-ch) [inline pkg/yurtctl/util/edgenode/common.go:66]: `/var/lib/yurthub` should be kept for yurthub certificates storage. and `/etc/kubernetes/pki` is not need to added because `/etc/kubernetes` hostpath has already mounted.

File: pkg/yurtctl/util/edgenode/common.go (hunk 1 above)
Comment (rambohe-ch) [reply pkg/yurtctl/util/edgenode/common.go:85]: @Windrow `join-token` can be generated by yurtctl, and we suggest that use hubself mode with `join-token` to generate yurthub client certificate that used to connect kube-apiserver.  so we need to keep `--join-token` parameter for yurthub.

File: pkg/yurtctl/cmd/revert/edgenode.go [hunk 3]
```diff
@@ -310,3 +318,7 @@ func (r *RevertEdgeNodeOptions) getKubeletSvcBackup() string {
 func (r *RevertEdgeNodeOptions) getYurthubYaml() string {
 	return filepath.Join(r.PodMainfestPath, enutil.YurthubYamlName)
 }
+
+func (r *RevertEdgeNodeOptions) getYurthubConf() string {
+	return filepath.Join(hubself.HubRootDir, hubself.HubName)
```
Comment (rambohe-ch) [inline pkg/yurtctl/cmd/revert/edgenode.go:323]: Var HubRootDir is not found in hubself package

**Comment by rambohe-ch** [comment]
@Windrow Thank you for making up pull request.
please fix the following ci errors.

File: pkg/yurtctl/cmd/revert/edgenode.go (hunk 3 above)
Comment (Windrow) [inline pkg/yurtctl/cmd/revert/edgenode.go]:
```suggestion
	return filepath.Join(hubself.hubRootDir, hubself.hubName)
```

Comment (Windrow) [reply pkg/yurtctl/cmd/revert/edgenode.go]: @rambohe-ch 
Sorry, my mistake.

Comment (Windrow) [reply pkg/yurtctl/cmd/revert/edgenode.go]:
```
 func (r *RevertEdgeNodeOptions) getYurthubConf() string {
-       return filepath.Join(hubself.HubRootDir, hubself.HubName)
+       return filepath.Join(hubself.hubRootDir, hubself.hubName)
 }
```

Sorry, my mistake.

**Comment by rambohe-ch** [comment]
@Windrow please fix the following ci errors.

File: pkg/yurthub/certificate/hubself/cert_mgr.go [hunk 4]
```diff
@@ -85,6 +86,26 @@ type yurtHubCertManager struct {
 	stopCh                chan struct{}
 }
 
+// GetYurthubConfRootDir
+func GetYurthubConfRootDir() string {
```
Comment (rambohe-ch) [inline pkg/yurthub/certificate/hubself/cert_mgr.go:90]: how about change `hubRootDir` to `HubRootDir`? so yurtctl can use `HubRootDir` directly.  and `GetYurthubConfRootDir ` func is not need to add.

Comment (Windrow) [reply pkg/yurthub/certificate/hubself/cert_mgr.go:90]: In NewYurtHubCertManager, rootDir is got in the same way, from config first.
```
        hn := projectinfo.GetHubName()
        if len(hn) == 0 {
                hn = hubName
        }

        rootDir := cfg.RootDir
        if len(rootDir) == 0 {
                rootDir = filepath.Join(hubRootDir, hn)
        }
```

But yes, I think it is okay to simply clear the default path, since nobody bothers to use different config XD

**Comment by rambohe-ch** [comment]
@Windrow please fix the following ci errors.
