### PR TITLE
When yurtctl revert executes yurtappmanager to delete automatically, no crd resource error is reported.

### LINKED ISSUE #557: When yurtctl revert executes yurtappmanager to delete automatically, no crd resource error is reported.
**What happened**:
If yurtappmanager is not deployed and yurtctl revert is executed, a notfound error will be reported when yurtappmanager is deleted.
**What you expected to happen**:

A not found error occurred
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

### PR DESCRIPTION
**Pull request by yanyhui**
…D resource error

/kind bug

#### What this PR does / why we need it:
Yurtappmanager does not use the method of deleting crd resources when crd is not deployed.
#### Which issue(s) this PR fixes:

Fixes #557 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/yurtctl/util/kubernetes/util.go [hunk 1]
```diff
@@ -31,12 +31,14 @@ import (
 	"sync"
 	"time"
 
+	"github.com/spf13/pflag"
```
Comment (rambohe-ch) [inline pkg/yurtctl/util/kubernetes/util.go:34]: please make go-imports.

**Review by rambohe-ch — APPROVED** [review]
