### PR TITLE
bugfix: fix querying local empty list error

### LINKED ISSUE #325: [BUG] When the cloud and the edge were disconnected and a List request is made for an empty CR, the edge responded with an error
**What happened**:

When the cloud and edge are disconnected, and a List request is made for a registered CR, if the number of this custom resources is zero, normally, Yurthub should return an empty CRD List response, as follows:

```json
{"apiVersion":"stable.example.com/v1","items":[],"kind":"CronTabList","metadata":{"continue":"","resourceVersion":"2616035","selfLink":"/apis/stable.example.com/v1/namespaces/default/crontabs"}}
```

But in fact, the error message is returned as follows:

```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: no matches for stable.example.com/v1, Resource=crontabs","reason":"InternalError","details":{"causes":[{"message":"no matches for stable.example.com/v1, Resource=crontabs"}]},"code":500}
```

**What you expected to happen**:

- When the connection between cloud and edge is normal and the List operation is performed for CR, the corresponding CRD information should be saved even if the number of resources is empty.
- When the cloud and edges are disconnected, and a List request is made for an empty number of CR resources
  - If CRD is registered , empty structure will be returned
  - If CRD is not registered , an error message will be returned

**How to reproduce it (as minimally and precisely as possible)**:

1. Register a CRD but do not create any resources
2. When the communication between the cloud and the edge is normal, make a list request for this CR
   - You will get the correct reply message with empty list structure
3. When the cloud and the edge are disconnected, make a list request for this CR resource
   - You will get the error message

**Anything else we need to know?**:

**Environment**:

- OpenYurt version: the latest version
- Kubernetes version (use `kubectl version`):

```sh
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g: `cat /etc/os-release`):

```sh
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`):

```sh
Linux master 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
- Others:

**others**

/kind bug

### PR DESCRIPTION
**Pull request by qclc**
/kind bug

#### What this PR does / why we need it:
1. Add DynamicRESTMapper to store GVK and GVR mappings for non-built-in resources, while providing dynamic update function.
2. Fix error: when the cloud and edge are disconnected, and a List request is made for a registered CR, if the number of this custom resource is zero, edge return the wrong message.
3. Add unit tests to verify new feature

#### Which issue(s) this PR fixes:

Fixes #325 

#### Special notes for your reviewer:

/assign @rambohe-ch 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/yurthub/cachemanager/cache_manager.go [hunk 1]
```diff
@@ -146,21 +146,27 @@ func (cm *cacheManager) queryListObject(req *http.Request) (runtime.Object, erro
...
-	var gvk schema.GroupVersionKind
 	var kind string
 	objs, err := cm.storage.List(key)
-	if err != nil {
-		return nil, err
-	} else if len(objs) == 0 {
-		gvk, err = serializer.UnsafeDefaultRESTMapper.KindFor(schema.GroupVersionResource{
+	// storage.ErrStorageNotFound indicates that there is no corresponding resource locally,
+	// and will determine whether to return an empty list structure according to whether GVK is registered or not
+	if err == storage.ErrStorageNotFound {
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager.go:153]: 1. storage.ErrStorageNotFound does not indicates empty list object on local disk, and indicates an error that request resource is not cached in local disk, so we need to return error here. 
2. and `len(objs)==0` indicates empty list object on local disk.

File: pkg/yurthub/cachemanager/cache_manager.go [hunk 2]
```diff
@@ -146,21 +146,27 @@ func (cm *cacheManager) queryListObject(req *http.Request) (runtime.Object, erro
...
+		gvr := schema.GroupVersionResource{
 			Group:    info.APIGroup,
 			Version:  info.APIVersion,
 			Resource: info.Resource,
-		})
-		if err != nil {
-			return nil, err
+		}
+		gvk, e := serializer.YurtHubRESTMapperManager.UnsafeDefaultRESTMapper.KindFor(gvr)
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager.go:159]: It's not good to expose `RESTMaaper` info out of serializer, how about add a func `KindFor()` for serializer?

File: pkg/yurthub/cachemanager/cache_manager_test.go [hunk 3]
```diff
@@ -1047,35 +1046,6 @@ func TestCacheListResponse(t *testing.T) {
...
-			path:       "/apis/node.k8s.io/v1beta1/runtimeclasses",
-			resource:   "runtimeclasses",
-			namespaced: false,
-			expectResult: struct {
-				err  bool
-				data map[string]struct{}
-			}{
-				data: map[string]struct{}{},
-			},
-		},
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager_test.go:1078]: It's need to keep these test case.

File: pkg/yurthub/cachemanager/cache_manager_test.go [hunk 4]
```diff
@@ -2080,54 +2080,55 @@ func TestQueryCacheForList(t *testing.T) {
...
-			namespaced: false,
-			expectResult: struct {
-				err  bool
-				rv   string
-				data map[string]struct{}
-			}{
-				err: true,
-			},
-			queryErr: storage.ErrStorageNotFound,
-		},
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager_test.go:2130]: we need to keep these test cases.

File: pkg/yurthub/proxy/remote/remote.go [hunk 5]
```diff
@@ -101,6 +103,21 @@ func (rp *RemoteProxy) modifyResponse(resp *http.Response) error {
 				h.Add("Transfer-Encoding", "chunked")
 			}
 		}
+
+		// 404 Not Found: The CRD may have been unregistered and should be updated locally as well
+		if resp.StatusCode == http.StatusNotFound {
```
Comment (rambohe-ch) [inline pkg/yurthub/proxy/remote/remote.go:108]: I think it's not need to cache CRD kind info on node local when CRD is not exist in cluster.

File: pkg/yurthub/kubernetes/serializer/serializer.go [hunk 6]
```diff
@@ -39,27 +43,211 @@ import (
...
+	// storageEnabled is used to determine whether to enable hard cache
+	storageEnabled bool
+	// Used to hard cache the resourceToKind
+	storage        storage.Store
+	resourceToKind map[schema.GroupVersionResource]schema.GroupVersionKind
+}
+
+func NewDynamicRESTMapper() *DynamicRESTMapper {
+	m := make(map[schema.GroupVersionResource]schema.GroupVersionKind)
+	s, err := factory.CreateStorage()
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/serializer/serializer.go:69]: do not create Storage here, how about use the `StorageWrapper` from  `YurtHubConfiguration`?

File: pkg/yurthub/kubernetes/serializer/serializer.go [hunk 7]
```diff
@@ -39,27 +43,211 @@ import (
...
+// Used to add and update the mapping relationship between GVR and GVK
+func (dm *DynamicRESTMapper) UpdateGVK(gvk schema.GroupVersionKind) error {
+	dm.Lock()
+	defer dm.Unlock()
+	kindName := strings.TrimSuffix(gvk.Kind, "List")
+	plural, singular := meta.UnsafeGuessKindToResource(gvk.GroupVersion().WithKind(kindName))
+	dm.resourceToKind[singular] = gvk
+	dm.resourceToKind[plural] = gvk
+
+	return dm.updateCachedDynamicRESTMapper()
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/serializer/serializer.go:124]: make sure no duplicate update cache if GVK has been updated.

File: pkg/yurthub/proxy/remote/remote.go [hunk 8]
```diff
@@ -101,6 +103,21 @@ func (rp *RemoteProxy) modifyResponse(resp *http.Response) error {
...
+			gvr := schema.GroupVersionResource{
+				Group:    info.APIGroup,
+				Version:  info.APIVersion,
+				Resource: info.Resource,
+			}
+			gvk, err := serializer.YurtHubRESTMapperManager.CRDRESTMapper.KindFor(gvr)
```
Comment (rambohe-ch) [inline pkg/yurthub/proxy/remote/remote.go:114]: please try do not reference `serializer.YurtHubRESTMapperManager` out of `serializer`

File: pkg/yurthub/cachemanager/cache_manager.go (hunk 1 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager.go]: Thanks for reminding me. I ignored this situation. The PR submitted recently corrected this mistake

File: pkg/yurthub/cachemanager/cache_manager.go (hunk 2 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager.go]: I combined RESTMapperManager with CacheManager, and the interface is exposed by CacheManager

File: pkg/yurthub/cachemanager/cache_manager.go [hunk 9]
```diff
@@ -346,22 +352,25 @@ func (cm *cacheManager) saveListObject(ctx context.Context, info *apirequest.Req
...
-		return cm.storage.Create(key, nil)
-	} else if info.Name != "" && len(items) == 1 {
+
+	// For CRD, if no objects in cloud cluster, we need to store the GVK info of CRD,
+	// so when cloud-edge network disconnected,
+	// yurthub can return empty objects(make by using GVK info) instead of 404 code(not found)
+
+	// Verify if DynamicRESTMapper(which store the CRD info) needs to be updated
+	gvk := apiVersion.WithKind(kind)
+	if err = serializer.YurtHubRESTMapperManager.UpdateCRDRESTMapper(gvk); err != nil {
```
[the remark this answers is not in the document]
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager.go]: I combined RESTMapperManager with CacheManager, and the interface is exposed by CacheManager

File: pkg/yurthub/cachemanager/cache_manager.go [hunk 10]
```diff
@@ -346,22 +352,25 @@ func (cm *cacheManager) saveListObject(ctx context.Context, info *apirequest.Req
...
-	}.String()
+	}
 	accessor := meta.NewAccessor()
 
 	comp, _ := util.ClientComponentFrom(ctx)
-	// even if no objects in cloud cluster, we need to
-	// make up a storage that represents the no resources
-	// in local disk, so when cloud-edge network disconnected,
-	// yurthub can return empty objects instead of 404 code(not found)
-	if len(items) == 0 {
```
[the remark this answers is not in the document]
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager.go]: Thanks for reminding. The PR submitted recently recovered this situation.

File: pkg/yurthub/cachemanager/cache_manager.go [hunk 11]
```diff
@@ -346,22 +352,25 @@ func (cm *cacheManager) saveListObject(ctx context.Context, info *apirequest.Req
...
-		// list returns no objects
-		key, _ := util.KeyFunc(comp, info.Resource, info.Namespace, "")
-		return cm.storage.Create(key, nil)
-	} else if info.Name != "" && len(items) == 1 {
+
+	// For CRD, if no objects in cloud cluster, we need to store the GVK info of CRD,
+	// so when cloud-edge network disconnected,
+	// yurthub can return empty objects(make by using GVK info) instead of 404 code(not found)
```
[the remark this answers is not in the document]
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager.go]: Thanks for reminding. The PR submitted recently corrected this mistake.

File: pkg/yurthub/cachemanager/cache_manager_test.go (hunk 3 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager_test.go]: The PR submitted recently recovered this test case.

File: pkg/yurthub/cachemanager/cache_manager_test.go (hunk 4 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager_test.go]: The PR submitted recently recovered this test case.

File: pkg/yurthub/kubernetes/serializer/serializer.go (hunk 6 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/serializer/serializer.go]: I combined RESTMapperManager with CacheManager, and the StorageWrapper of CacheManager will be used

File: pkg/yurthub/proxy/remote/remote.go (hunk 8 above)
Comment (qclc) [reply pkg/yurthub/proxy/remote/remote.go]: Thanks for reminding. I combined RESTMapperManager with CacheManager, and the interface will be exposed by CacheManager.

File: pkg/yurthub/kubernetes/serializer/serializer.go (hunk 7 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/serializer/serializer.go]: Thanks for reminding. The recently submitted PR adds validation logic.

File: pkg/yurthub/kubernetes/serializer/serializer.go [hunk 12]
```diff
@@ -42,24 +42,126 @@ import (
...
+		drm[gvr] = gvk
+	}
+
+	return &RESTMapperManager{
+		unsafeDefaultRESTMapper: mapper,
+		dynamicRESTMapper:       drm,
+	}
+}
+
+func (rm *RESTMapperManager) IsSchemeResource(gvr schema.GroupVersionResource) (bool, schema.GroupVersionKind) {
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/serializer/serializer.go:87]: I think it's not friendly to expose `RESTMapperManager` out of serializer.go, so we need to delete `IsSchemeResource` and `IsCustomResource` func, but add `KindFor` func for `Serializer` instead.

File: pkg/yurthub/cachemanager/cache_restmapper.go [hunk 13]
```diff
@@ -0,0 +1,110 @@
...
+	"k8s.io/apimachinery/pkg/runtime/schema"
+	"k8s.io/klog"
+)
+
+var (
+	cacheDynamicRESTMapperKey = "_internal/cache-manager/cache-crd-restmapper.conf"
+	sepForGVR                 = "/"
+)
+
+func (cm *cacheManager) initRESTMapperManager() {
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_restmapper.go:34]: In my opinion, `RESTMapper` info is not part of cacheManager, so it's not friendly to add func of `RESTMapper` in cacheManager. how about remove cache of restMapper into `serializer.go`?

File: pkg/yurthub/cachemanager/cache_manager.go [hunk 14]
```diff
@@ -52,12 +52,16 @@ type CacheManager interface {
 	UpdateCacheAgents(agents []string) error
 	ListCacheAgents() []string
 	CanCacheFor(req *http.Request) bool
+	UpdateKind(gvk schema.GroupVersionKind) error
+	DeleteKindFor(gvr schema.GroupVersionResource) error
+	ListCacheCRD() map[schema.GroupVersionResource]schema.GroupVersionKind
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager.go:57]: It's not friendly to add func of process `gvr` or `gvk` for cacheManager, In Original design, only `serializer.go` can process `gvr` and `gvk`

File: pkg/yurthub/kubernetes/serializer/serializer.go (hunk 12 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/serializer/serializer.go]: Thanks for the suggestion, the code has been updated.

File: pkg/yurthub/cachemanager/cache_restmapper.go (hunk 13 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_restmapper.go]: Thanks for the suggestion, the code has been updated.

File: pkg/yurthub/cachemanager/cache_manager.go (hunk 14 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager.go]: Thanks for the suggestion, the code has been updated.

File: pkg/yurthub/kubernetes/meta/restmapper.go [hunk 15]
```diff
@@ -0,0 +1,232 @@
...
+		// Recover the mapping relationship between GVR and GVK from the hard disk
+		b, err := dStorage.Get(CacheDynamicRESTMapperKey)
+		if err == nil && len(b) != 0 {
+			cacheMapper := make(map[string]string)
+			err = normaljson.Unmarshal(b, &cacheMapper)
+			if err != nil {
+				klog.Errorf("failed to get cached CRDRESTMapper, %v", err)
+			}
+
+			for gvrString, gvkString := range cacheMapper {
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/meta/restmapper.go:88]: gvkString --> kindString?

File: pkg/yurthub/kubernetes/meta/restmapper.go [hunk 16]
```diff
@@ -0,0 +1,232 @@
...
+	}
+	return mapper
+}
+
+func NewRESTMapperManager(rootDir string) *RESTMapperManager {
+	dm := make(map[schema.GroupVersionResource]schema.GroupVersionKind)
+	dStorage, err := disk.NewDiskStorage(rootDir)
+	if err == nil {
+		// Recover the mapping relationship between GVR and GVK from the hard disk
+		b, err := dStorage.Get(CacheDynamicRESTMapperKey)
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/meta/restmapper.go:80]: how about keep the format of `CacheDynamicRESTMapperKey` storage as the same of `dm := make(map[schema.GroupVersionResource]schema.GroupVersionKind)`, so format convert can be deleted and code will be more readable.

File: pkg/yurthub/cachemanager/cache_manager.go [hunk 17]
```diff
@@ -28,6 +28,7 @@ import (
 	"strings"
 	"sync"
 
+	meta2 "github.com/openyurtio/openyurt/pkg/yurthub/kubernetes/meta"
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager.go:31]: how about meta2 --> hubmeta?

File: pkg/yurthub/cachemanager/cache_manager_test.go [hunk 18]
```diff
@@ -29,6 +30,7 @@ import (
 	"time"
 
 	"github.com/openyurtio/openyurt/pkg/projectinfo"
+	meta2 "github.com/openyurtio/openyurt/pkg/yurthub/kubernetes/meta"
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager_test.go:33]: mata2 --> hubmeta?

File: pkg/yurthub/kubernetes/meta/restmapper.go [hunk 19]
```diff
@@ -0,0 +1,232 @@
...
+)
+
+const (
+	CacheDynamicRESTMapperKey = "_internal/restmapper/cache-crd-restmapper.conf"
+	SepForGVR                 = "/"
+)
+
+var (
+	// unsafeDefaultRESTMapper is used to store the mapping relationship between GVK and GVR in scheme
+	unsafeDefaultRESTMapper = NewDefaultRESTMapperFromScheme()
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/meta/restmapper.go:41]: var `unsafeDefaultRESTMapper` has the same name as struct field `RESTMapperManager. unsafeDefaultRESTMapper`, we need different these two definitions.

File: pkg/yurthub/kubernetes/meta/restmapper.go [hunk 20]
```diff
@@ -0,0 +1,232 @@
...
+		}
+	}
+	return schema.GroupVersionKind{}, fmt.Errorf("no matches for %v", resource)
+}
+
+// Used to delete the mapping relationship between GVR and GVK in dynamicRESTMapper
+func (rm *RESTMapperManager) deleteKind(gvk schema.GroupVersionKind) error {
+	rm.Lock()
+	kindName := strings.TrimSuffix(gvk.Kind, "List")
+	plural, singular := meta.UnsafeGuessKindToResource(gvk.GroupVersion().WithKind(kindName))
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/meta/restmapper.go:156]:
```
	kindName := strings.TrimSuffix(gvk.Kind, "List")
	plural, singular := meta.UnsafeGuessKindToResource(gvk.GroupVersion().WithKind(kindName))
```
should be located before `rm.Lock()`

File: pkg/yurthub/proxy/remote/loadbalancer.go [hunk 21]
```diff
@@ -25,8 +25,11 @@ import (
 	"github.com/openyurtio/openyurt/pkg/yurthub/cachemanager"
 	"github.com/openyurtio/openyurt/pkg/yurthub/certificate/interfaces"
 	"github.com/openyurtio/openyurt/pkg/yurthub/healthchecker"
+	"github.com/openyurtio/openyurt/pkg/yurthub/kubernetes/meta"
+	util2 "github.com/openyurtio/openyurt/pkg/yurthub/proxy/util"
```
Comment (rambohe-ch) [inline pkg/yurthub/proxy/remote/loadbalancer.go:29]: util2 --> proxyutil?

File: pkg/yurthub/proxy/util/util.go [hunk 22]
```diff
@@ -292,3 +294,28 @@ func WithRequestTimeout(handler http.Handler) http.Handler {
 		handler.ServeHTTP(w, req)
 	})
 }
+
+// WithUpdateRESTMapper used to update the RESTMapper.
+func WithUpdateRESTMapper(handler http.Handler, manager *meta.RESTMapperManager) http.Handler {
```
Comment (rambohe-ch) [inline pkg/yurthub/proxy/util/util.go:299]: why not put all of restMapper operations in this func?

File: pkg/yurthub/storage/disk/storage.go [hunk 23]
```diff
@@ -87,6 +88,21 @@ func (ds *diskStorage) Create(key string, contents []byte) error {
 			}
 			return err
 		} else if info.IsDir() {
+			// ensure that there are no files left locally before create an dir
+			if fileInfoList, err := ioutil.ReadDir(keyPath); err != nil {
```
Comment (rambohe-ch) [inline pkg/yurthub/storage/disk/storage.go:92]: `ioutil.ReadDir(keyPath)` will return a sorted list files, but we only need to list all file names, so how about use the following code:
```
    f, err := os.Open(keyPath)
    if err != nil {
        return err
    }
    defer f.Close()
    names, err := f.Readdirnames(-1)
    if err != nil {
        return err
    }
```

File: pkg/yurthub/cachemanager/cache_manager_test.go (hunk 18 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager_test.go]: The code is updated.

File: pkg/yurthub/cachemanager/cache_manager.go (hunk 17 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager.go]: The code is updated.

File: pkg/yurthub/kubernetes/meta/restmapper.go (hunk 15 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/meta/restmapper.go]: The code is updated.

File: pkg/yurthub/kubernetes/meta/restmapper.go (hunk 20 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/meta/restmapper.go:136]: The code is updated.

File: pkg/yurthub/proxy/remote/loadbalancer.go (hunk 21 above)
Comment (qclc) [reply pkg/yurthub/proxy/remote/loadbalancer.go]: The code is updated.

File: pkg/yurthub/storage/disk/storage.go (hunk 23 above)
Comment (qclc) [reply pkg/yurthub/storage/disk/storage.go]: The code is updated, the Create(..) no longer cleans up old files, and the related functions are placed in the Replace(..).

File: pkg/yurthub/kubernetes/meta/restmapper.go (hunk 19 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/meta/restmapper.go]: The code is updated, the global variable name is changed to `unsafeSchemeRESTMapper`.

File: pkg/yurthub/kubernetes/meta/restmapper.go (hunk 16 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/meta/restmapper.go:83]: The code has been updated to extract the relevant conversion logic.

File: pkg/yurthub/cachemanager/cache_manager.go [hunk 24]
```diff
@@ -600,3 +625,8 @@ func (cm *cacheManager) CanCacheFor(req *http.Request) bool {
 	}
 	return true
 }
+
+// DeleteInvalidKindFor is used to delete the invalid Kind(which is not registered in the cloud)
+func (cm *cacheManager) DeleteInvalidKindFor(gvr schema.GroupVersionResource) error {
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager.go:630]: how about change the func name from `DeleteInvalidKindFor` to `DeleteKindFor`?

File: pkg/yurthub/cachemanager/cache_manager_test.go [hunk 25]
```diff
@@ -2237,13 +2354,46 @@ func compareObjectsAndKeys(t *testing.T, objs []runtime.Object, namespaced bool,
 	return true
 }
 
+//used to reset the RESTMapper
+func resetRESTMapper(dStorage storage.Store, rm *hubmeta.RESTMapperManager) error {
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager_test.go:2358]: please add a `reset` func for `RESTMapperManager`

File: pkg/yurthub/cachemanager/cache_manager_test.go [hunk 26]
```diff
@@ -1098,7 +1115,7 @@ func TestCacheListResponse(t *testing.T) {
 			path:       "/api/v1/node",
 			resource:   "nodes",
 			namespaced: false,
-			cacheErr:   storage.ErrStorageNotFound,
+			queryErr:   storage.ErrStorageNotFound,
```
Comment (rambohe-ch) [inline pkg/yurthub/cachemanager/cache_manager_test.go:1118]: I think we only need `expectResult` to verify the return values, so please delete `cacheErr` or `queryErr` field.

File: pkg/yurthub/cachemanager/cache_manager.go (hunk 24 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager.go]: The code has been updated, please review.

File: pkg/yurthub/cachemanager/cache_manager_test.go (hunk 25 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager_test.go]: The code has been updated, please review.

File: pkg/yurthub/cachemanager/cache_manager_test.go (hunk 26 above)
Comment (qclc) [reply pkg/yurthub/cachemanager/cache_manager_test.go]: The code has been updated, please review.

File: pkg/yurthub/kubernetes/meta/restmapper.go [hunk 27]
```diff
@@ -0,0 +1,259 @@
...
+				mapper.Add(gv.WithKind(kind), scope)
+			}
+		}
+	}
+	return mapper
+}
+
+func NewRESTMapperManager(rootDir string) *RESTMapperManager {
+	var dm map[schema.GroupVersionResource]schema.GroupVersionKind
+	dStorage, err := disk.NewDiskStorage(rootDir)
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/meta/restmapper.go:80]: why not make `disk storage` as parameter for `NewRESTMapperManager`?

File: pkg/yurthub/kubernetes/meta/restmapper.go [hunk 28]
```diff
@@ -0,0 +1,259 @@
...
+		b, err := dStorage.Get(CacheDynamicRESTMapperKey)
+		if err == nil && len(b) != 0 {
+			dm = unmarshalDynamicRESTMapper(b)
+			klog.Infof("reset DynamicRESTMapper to %v", dm)
+		} else {
+			dm = make(map[schema.GroupVersionResource]schema.GroupVersionKind)
+			klog.Infof("initialize an empty DynamicRESTMapper")
+		}
+	} else {
+		klog.Errorf("failed to create disk storage, %v, only initialize an empty DynamicRESTMapper in memory ", err)
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/meta/restmapper.go:92]: if failed to create disk storage, i think we need to return error.

File: pkg/yurthub/kubernetes/meta/restmapper.go [hunk 29]
```diff
@@ -0,0 +1,259 @@
...
+		return rm.updateCachedDynamicRESTMapper()
+	}
+	return nil
+}
+
+// ResetRESTMapper is used to clean up all cached GVR/GVK information in DynamicRESTMapper,
+// and delete the corresponding file in the disk (cache-crd-restmapper.conf), it should be used carefully.
+func (rm *RESTMapperManager) ResetRESTMapper() error {
+	rm.dynamicRESTMapper = make(map[schema.GroupVersionResource]schema.GroupVersionKind)
+	err := rm.storage.DeleteCollection("_internal/restmapper")
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/meta/restmapper.go:204]: `_internal/restmapper` is hard code, please define a constant var.

File: pkg/yurthub/kubernetes/meta/restmapper.go [hunk 30]
```diff
@@ -0,0 +1,259 @@
...
+		dynamicRESTMapper:       dm,
+		storage:                 dStorage,
+	}
+}
+
+// Obtain gvk according to gvr in dynamicRESTMapper
+func (rm *RESTMapperManager) dynamicKindFor(gvr schema.GroupVersionResource) (schema.GroupVersionKind, error) {
+	rm.RLock()
+	defer rm.RUnlock()
+	resource := gvr
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/meta/restmapper.go:106]: I think var resource is not needed, we can use gvr directly.

File: pkg/yurthub/kubernetes/meta/restmapper.go [hunk 31]
```diff
@@ -0,0 +1,259 @@
...
+		unsafeDefaultRESTMapper: unsafeSchemeRESTMapper,
+		dynamicRESTMapper:       dm,
+		storage:                 dStorage,
+	}
+}
+
+// Obtain gvk according to gvr in dynamicRESTMapper
+func (rm *RESTMapperManager) dynamicKindFor(gvr schema.GroupVersionResource) (schema.GroupVersionKind, error) {
+	rm.RLock()
+	defer rm.RUnlock()
```
Comment (rambohe-ch) [inline pkg/yurthub/kubernetes/meta/restmapper.go:105]:
```
	rm.RLock()
	defer rm.RUnlock()
```

code block can be moved to before `if hasVersion` condition.

Comment (qclc) [reply pkg/yurthub/kubernetes/meta/restmapper.go]: The code is updated, and code block is removed.

File: pkg/yurthub/kubernetes/meta/restmapper.go (hunk 30 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/meta/restmapper.go]: The code is updated, please review.

File: pkg/yurthub/kubernetes/meta/restmapper.go (hunk 29 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/meta/restmapper.go]: The code is updated, please review.

File: pkg/yurthub/kubernetes/meta/restmapper.go (hunk 27 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/meta/restmapper.go]: The code is updated, the `disk storage` is passed into the `NewRESTMapperManager` as a variable.

File: pkg/yurthub/kubernetes/meta/restmapper.go (hunk 28 above)
Comment (qclc) [reply pkg/yurthub/kubernetes/meta/restmapper.go]: The code is updated, the `disk storage` is passed into the `NewRESTMapperManager` as a variable, so the storage creation process is deleted.

**Comment by qclc** [comment]
- Kubernetes version (use `kubectl version`):
```sh
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyunedge.1", GitCommit:"d0a01f1", GitTreeState:"", BuildDate:"2021-05-24T03:00:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
```sh
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```
- Startup log:
```sh
yurthub version: projectinfo.Info{GitVersion:"v0.8.6", GitCommit:"0476391", BuildDate:"2021-07-30T06:43:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
I0730 06:48:53.014993       1 start.go:61] FLAG: --access-server-through-hub="false"
I0730 06:48:53.015024       1 start.go:61] FLAG: --add_dir_header="false"
I0730 06:48:53.015029       1 start.go:61] FLAG: --alsologtostderr="false"
I0730 06:48:53.015034       1 start.go:61] FLAG: --bind-address="127.0.0.1"
I0730 06:48:53.015039       1 start.go:61] FLAG: --cert-mgr-mode="hubself"
I0730 06:48:53.015043       1 start.go:61] FLAG: --disabled-resource-filters="[]"
I0730 06:48:53.015048       1 start.go:61] FLAG: --disk-cache-path="/etc/kubernetes/cache/"
I0730 06:48:53.015052       1 start.go:61] FLAG: --dummy-if-ip="169.254.2.1"
I0730 06:48:53.015055       1 start.go:61] FLAG: --dummy-if-name="yurthub-dummy0"
I0730 06:48:53.015059       1 start.go:61] FLAG: --enable-dummy-if="true"
I0730 06:48:53.015062       1 start.go:61] FLAG: --enable-iptables="true"
I0730 06:48:53.015065       1 start.go:61] FLAG: --enable-resource-filter="true"
I0730 06:48:53.015068       1 start.go:61] FLAG: --gc-frequency="120"
I0730 06:48:53.015073       1 start.go:61] FLAG: --heartbeat-failed-retry="3"
I0730 06:48:53.015076       1 start.go:61] FLAG: --heartbeat-healthy-threshold="2"
I0730 06:48:53.015079       1 start.go:61] FLAG: --heartbeat-timeout-seconds="2"
I0730 06:48:53.015082       1 start.go:61] FLAG: --help="false"
I0730 06:48:53.015086       1 start.go:61] FLAG: --join-token="abc"
I0730 06:48:53.015099       1 start.go:61] FLAG: --kubelet-ca-file="/etc/kubernetes/pki/ca.crt"
I0730 06:48:53.015103       1 start.go:61] FLAG: --kubelet-client-certificate="/var/lib/kubelet/pki/kubelet-client-current.pem"
I0730 06:48:53.015108       1 start.go:61] FLAG: --lb-mode="rr"
I0730 06:48:53.015111       1 start.go:61] FLAG: --log-flush-frequency="5s"
I0730 06:48:53.015116       1 start.go:61] FLAG: --log_backtrace_at=":0"
I0730 06:48:53.015135       1 start.go:61] FLAG: --log_dir=""
I0730 06:48:53.015139       1 start.go:61] FLAG: --log_file=""
I0730 06:48:53.015142       1 start.go:61] FLAG: --log_file_max_size="1800"
I0730 06:48:53.015145       1 start.go:61] FLAG: --logtostderr="true"
I0730 06:48:53.015148       1 start.go:61] FLAG: --max-requests-in-flight="250"
I0730 06:48:53.015152       1 start.go:61] FLAG: --node-name="n137"
I0730 06:48:53.015155       1 start.go:61] FLAG: --profiling="true"
I0730 06:48:53.015158       1 start.go:61] FLAG: --proxy-port="10261"
I0730 06:48:53.015161       1 start.go:61] FLAG: --root-dir="/var/lib/yurthub"
I0730 06:48:53.015164       1 start.go:61] FLAG: --serve-port="10267"
I0730 06:48:53.015167       1 start.go:61] FLAG: --server-addr="https://x.x.x.x:6443"
I0730 06:48:53.015170       1 start.go:61] FLAG: --skip_headers="false"
I0730 06:48:53.015173       1 start.go:61] FLAG: --skip_log_headers="false"
I0730 06:48:53.015176       1 start.go:61] FLAG: --stderrthreshold="2"
I0730 06:48:53.015180       1 start.go:61] FLAG: --v="2"
I0730 06:48:53.015183       1 start.go:61] FLAG: --version="false"
I0730 06:48:53.015186       1 start.go:61] FLAG: --vmodule=""
I0730 06:48:53.015206       1 config.go:172] yurthub would connect remote servers: https://x.x.x.x:6443
I0730 06:48:53.016268       1 restmapper.go:86] initialize an empty DynamicRESTMapper
I0730 06:48:53.016610       1 filter.go:93] Filter servicetopology registered successfully
I0730 06:48:53.016624       1 filter.go:93] Filter masterservice registered successfully
I0730 06:48:53.016629       1 start.go:71] yurthub cfg: &config.YurtHubConfiguration{LBMode:"rr", RemoteServers:[]*url.URL{(*url.URL)(0xc00056c900)}, YurtHubServerAddr:"127.0.0.1:10267", YurtHubProxyServerAddr:"127.0.0.1:10261", YurtHubProxyServerDummyAddr:"169.254.2.1:10261", GCFrequency:120, CertMgrMode:"hubself", KubeletRootCAFilePath:"/etc/kubernetes/pki/ca.crt", KubeletPairFilePath:"/var/lib/kubelet/pki/kubelet-client-current.pem", NodeName:"n137", HeartbeatFailedRetry:3, HeartbeatHealthyThreshold:2, HeartbeatTimeoutSeconds:2, MaxRequestInFlight:250, JoinToken:"abc", RootDir:"/var/lib/yurthub", EnableProfiling:true, EnableDummyIf:true, EnableIptables:true, HubAgentDummyIfName:"yurthub-dummy0", StorageWrapper:(*cachemanager.storageWrapper)(0xc0000ade40), SerializerManager:(*serializer.SerializerManager)(0xc0000ade80), RESTMapperManager:(*meta.RESTMapperManager)(0xc0000adec0), MutatedMasterServiceAddr:"x.x.x.x:6443", Filters:(*filter.Filters)(0xc00049e810), SharedFactory:(*informers.sharedInformerFactory)(0xc000163270), YurtSharedFactory:(*externalversions.sharedInformerFactory)(0xc0001632c0)}
I0730 06:48:53.016685       1 start.go:86] 1. register cert managers
I0730 06:48:53.016692       1 certificate.go:60] Registered certificate manager kubelet
I0730 06:48:53.016697       1 certificate.go:60] Registered certificate manager hubself
I0730 06:48:53.016700       1 start.go:92] 2. create cert manager with hubself mode
I0730 06:48:53.016720       1 cert_mgr.go:214] /var/lib/yurthub/pki/ca.crt file already exists, so skip to create ca file
I0730 06:48:53.016731       1 cert_mgr.go:127] use /var/lib/yurthub/pki/ca.crt ca file to bootstrap yurthub
I0730 06:48:53.016800       1 cert_mgr.go:289] yurthub bootstrap conf file already exists, skip init bootstrap
I0730 06:48:53.016828       1 certificate_store.go:130] Loading cert/key pair from "/var/lib/yurthub/pki/yurthub-current.pem".
I0730 06:48:53.026366       1 certificate_manager.go:282] Certificate rotation is enabled.
I0730 06:48:53.026405       1 cert_mgr.go:412] yurthub config file already exists, skip init config file
I0730 06:48:53.026412       1 start.go:100] 3. new transport manager
I0730 06:48:53.026417       1 transport.go:57] use /var/lib/yurthub/pki/ca.crt ca cert file to access remote server
I0730 06:48:53.026522       1 start.go:108] 4. create health checker for remote servers 
I0730 06:48:53.026525       1 certificate_manager.go:553] Certificate expiration is 2031-07-27 08:44:12 +0000 UTC, rotation deadline is 2029-06-16 19:44:56.161229204 +0000 UTC
I0730 06:48:53.026547       1 certificate_manager.go:288] Waiting 69084h56m3.13468415s for next certificate rotation
I0730 06:48:53.031311       1 connrotation.go:145] create a connection from 192.168.0.137:34152 to x.x.x.x:6443, total 1 connections in transport manager dialer
I0730 06:48:53.059469       1 start.go:117] 5. new restConfig manager for hubself mode
I0730 06:48:53.059486       1 start.go:125] 6. new cache manager with storage wrapper and serializer manager
I0730 06:48:53.059519       1 cache_agent.go:69] reset cache agents to [kubelet kube-proxy flanneld coredns yurttunnel-agent yurthub]
I0730 06:48:53.061985       1 start.go:133] 7. new gc manager for node n137, and gc frequency is a random time between 120 min and 360 min
I0730 06:48:53.062077       1 gc.go:97] list pod keys from storage, total: 5
I0730 06:48:53.063052       1 config.go:107] re-fix hub rest config host successfully with server https://x.x.x.x:6443
I0730 06:48:53.094471       1 gc.go:125] list all of pod that on the node: total: 5
I0730 06:48:53.094505       1 start.go:142] 8. new filter chain for mutating response body
I0730 06:48:53.094545       1 filter.go:70] Filter servicetopology initialize successfully
I0730 06:48:53.094558       1 filter.go:70] Filter masterservice initialize successfully
I0730 06:48:53.094564       1 start.go:150] 9. new reverse proxy handler for remote servers
I0730 06:48:53.094582       1 start.go:159] 10. create dummy network interface yurthub-dummy0 and init iptables manager
I0730 06:48:53.094626       1 gc.go:74] start gc events after waiting 121.535µs from previous gc
I0730 06:48:53.095162       1 config.go:107] re-fix hub rest config host successfully with server https://x.x.x.x:6443
I0730 06:48:53.096272       1 gc.go:163] list kubelet event keys from storage, total: 7
I0730 06:48:53.136733       1 gc.go:160] no kube-proxy events in local storage, skip kube-proxy events gc
I0730 06:48:53.139492       1 start.go:167] 11. new yurthub server and begin to serve, dummy proxy server: 169.254.2.1:10261
I0730 06:48:53.139515       1 start.go:176] 11. new yurthub server and begin to serve, proxy server: 127.0.0.1:10261, hub server: 127.0.0.1:10267
I0730 06:48:53.139573       1 reflector.go:175] Starting reflector *v1.Service (24h0m0s) from pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125
I0730 06:48:53.139718       1 reflector.go:175] Starting reflector *v1alpha1.NodePool (24h0m0s) from pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125
E0730 06:48:53.139913       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125: Failed to list *v1.Service: Get http://127.0.0.1:10261/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:10261: connect: connection refused
E0730 06:48:53.139957       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125: Failed to list *v1alpha1.NodePool: Get http://127.0.0.1:10261/apis/apps.openyurt.io/v1alpha1/nodepools?limit=500&resourceVersion=0: dial tcp 127.0.0.1:10261: connect: connection refused
I0730 06:48:53.361313       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dkube-proxy&resourceVersion=2605285&timeout=6m24s&timeoutSeconds=384&watch=true, in flight requests: 1
I0730 06:48:53.361499       1 util.go:232] start proxying: get /api/v1/services?allowWatchBookmarks=true&resourceVersion=1245131&timeout=8m15s&timeoutSeconds=495&watch=true, in flight requests: 2
I0730 06:48:53.361683       1 util.go:232] start proxying: get /apis/network.openyurt.io/v1alpha1/nodenetworkconfigurations?allowWatchBookmarks=true&resourceVersion=1255477&timeout=5m50s&timeoutSeconds=350&watch=true, in flight requests: 3
I0730 06:48:53.362320       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dyurttunnel-nodes&resourceVersion=2602494&timeout=5m41s&timeoutSeconds=341&watch=true, in flight requests: 4
I0730 06:48:53.362379       1 util.go:232] start proxying: get /api/v1/namespaces?allowWatchBookmarks=true&resourceVersion=1241767&timeout=8m55s&timeoutSeconds=535&watch=true, in flight requests: 5
I0730 06:48:53.363291       1 util.go:232] start proxying: get /apis/discovery.k8s.io/v1beta1/endpointslices?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=1255717&timeout=5m16s&timeoutSeconds=316&watch=true, in flight requests: 6
I0730 06:48:53.363323       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/secrets?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dkube-proxy-token-7fmxs&resourceVersion=2592959&timeout=7m29s&timeoutSeconds=449&watch=true, in flight requests: 7
I0730 06:48:53.363438       1 util.go:232] start proxying: get /api/v1/endpoints?allowWatchBookmarks=true&resourceVersion=1255718&timeout=5m55s&timeoutSeconds=355&watch=true, in flight requests: 8
I0730 06:48:53.363877       1 util.go:232] start proxying: get /api/v1/nodes?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dn137&resourceVersion=2613965&timeout=7m49s&timeoutSeconds=469&watch=true, in flight requests: 9
I0730 06:48:53.364401       1 util.go:232] start proxying: get /api/v1/services?allowWatchBookmarks=true&resourceVersion=1245131&timeoutSeconds=553&watch=true, in flight requests: 10
I0730 06:48:53.364925       1 util.go:232] start proxying: get /api/v1/services?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=1245131&timeout=9m1s&timeoutSeconds=541&watch=true, in flight requests: 11
I0730 06:48:53.365488       1 util.go:232] start proxying: get /api/v1/pods?allowWatchBookmarks=true&fieldSelector=spec.nodeName%3Dn137&resourceVersion=2614311&timeoutSeconds=537&watch=true, in flight requests: 12
I0730 06:48:53.366569       1 util.go:232] start proxying: get /apis/storage.k8s.io/v1/csidrivers?allowWatchBookmarks=true&resourceVersion=1241591&timeout=6m4s&timeoutSeconds=364&watch=true, in flight requests: 13
I0730 06:48:53.366857       1 serializer.go:199] schema.GroupVersionResource{Group:"network.openyurt.io", Version:"v1alpha1", Resource:"nodenetworkconfigurations"} is not found in client-go runtime scheme
I0730 06:48:53.367508       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dcoredns&resourceVersion=2606754&timeout=9m28s&timeoutSeconds=568&watch=true, in flight requests: 14
I0730 06:48:53.368916       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dkube-flannel-cfg&resourceVersion=2612031&timeout=7m15s&timeoutSeconds=435&watch=true, in flight requests: 15
I0730 06:48:53.370085       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/secrets?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dflannel-token-xgm5l&resourceVersion=2592959&timeout=6m25s&timeoutSeconds=385&watch=true, in flight requests: 16
I0730 06:48:53.371015       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/secrets?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dcoredns-token-dkfcc&resourceVersion=2592959&timeout=7m16s&timeoutSeconds=436&watch=true, in flight requests: 17
I0730 06:48:53.371951       1 util.go:232] start proxying: get /apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=1241589&timeout=6m38s&timeoutSeconds=398&watch=true, in flight requests: 18
I0730 06:48:53.373154       1 util.go:232] start proxying: get /api/v1/nodes?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dn137&resourceVersion=2613965&timeout=8m46s&timeoutSeconds=526&watch=true, in flight requests: 19
I0730 06:48:53.374080       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dalibaba-log-configuration&resourceVersion=2606034&timeout=7m49s&timeoutSeconds=469&watch=true, in flight requests: 20
I0730 06:48:53.375198       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/secrets?allowWatchBookmarks=true&fieldSelector=metadata.name%3Ddefault-token-bp6tc&resourceVersion=2592959&timeout=8m24s&timeoutSeconds=504&watch=true, in flight requests: 21
I0730 06:48:53.376286       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dcoredns-cloud&resourceVersion=2604342&timeout=5m57s&timeoutSeconds=357&watch=true, in flight requests: 22
I0730 06:48:53.803631       1 util.go:232] start proxying: post /api/v1/namespaces/kube-system/pods, in flight requests: 23
I0730 06:48:53.803648       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/pods/yurthub-n137, in flight requests: 24
I0730 06:48:53.812158       1 util.go:215] kubelet get pods: /api/v1/namespaces/kube-system/pods/yurthub-n137 with status code 404, spent 8.384195ms
I0730 06:48:53.821313       1 util.go:215] kubelet create pods: /api/v1/namespaces/kube-system/pods with status code 201, spent 17.608481ms
I0730 06:48:53.822869       1 cache_manager.go:468] skip to cache object because key(kubelet/pods/kube-system/yurthub-n137) is under processing
I0730 06:48:53.824568       1 cache_manager.go:323] pod(kubelet/pods/kube-system/yurthub-n137) is ADDED
I0730 06:48:53.977492       1 util.go:232] start proxying: get /api/v1/services?limit=500&resourceVersion=0, in flight requests: 23
I0730 06:48:53.983120       1 util.go:215] yurthub list services: /api/v1/services?limit=500&resourceVersion=0 with status code 200, spent 5.522897ms
I0730 06:48:53.984479       1 util.go:232] start proxying: get /api/v1/services?allowWatchBookmarks=true&resourceVersion=1245131&timeout=8m0s&timeoutSeconds=480&watch=true, in flight requests: 23
I0730 06:48:54.709158       1 util.go:232] start proxying: get /apis/apps.openyurt.io/v1alpha1/nodepools?limit=500&resourceVersion=0, in flight requests: 24
I0730 06:48:54.714847       1 util.go:215] yurthub list nodepools: /apis/apps.openyurt.io/v1alpha1/nodepools?limit=500&resourceVersion=0 with status code 200, spent 5.585613ms
I0730 06:48:54.714892       1 serializer.go:199] schema.GroupVersionResource{Group:"apps.openyurt.io", Version:"v1alpha1", Resource:"nodepools"} is not found in client-go runtime scheme
I0730 06:48:54.715954       1 util.go:232] start proxying: get /apis/apps.openyurt.io/v1alpha1/nodepools?allowWatchBookmarks=true&resourceVersion=2609783&timeout=7m3s&timeoutSeconds=423&watch=true, in flight requests: 24
I0730 06:48:55.445382       1 util.go:232] start proxying: put /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s, in flight requests: 25
I0730 06:48:55.445748       1 util.go:215] kubelet update leases: /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s with status code 200, spent 299.757µs
I0730 06:48:57.736739       1 util.go:232] start proxying: get /api/v1/namespaces/kube-system/pods/yurthub-n137, in flight requests: 25
I0730 06:48:57.745334       1 util.go:215] kubelet get pods: /api/v1/namespaces/kube-system/pods/yurthub-n137 with status code 200, spent 8.532597ms
I0730 06:48:57.745762       1 util.go:232] start proxying: patch /api/v1/namespaces/kube-system/pods/yurthub-n137/status, in flight requests: 25
I0730 06:48:57.756748       1 util.go:215] kubelet patch pods: /api/v1/namespaces/kube-system/pods/yurthub-n137/status with status code 200, spent 10.953107ms
I0730 06:48:57.757124       1 cache_manager.go:468] skip to cache object because key(kubelet/pods/kube-system/yurthub-n137) is under processing
I0730 06:48:57.758172       1 cache_manager.go:323] pod(kubelet/pods/kube-system/yurthub-n137) is MODIFIED
I0730 06:48:59.601362       1 util.go:232] start proxying: post /api/v1/namespaces/kube-system/events, in flight requests: 25
I0730 06:48:59.610948       1 util.go:215] kubelet create events: /api/v1/namespaces/kube-system/events with status code 201, spent 9.530534ms
I0730 06:48:59.611290       1 util.go:232] start proxying: post /api/v1/namespaces/kube-system/events, in flight requests: 25
I0730 06:48:59.620318       1 util.go:215] kubelet create events: /api/v1/namespaces/kube-system/events with status code 201, spent 8.996995ms
I0730 06:48:59.620560       1 util.go:232] start proxying: post /api/v1/namespaces/kube-system/events, in flight requests: 25
I0730 06:48:59.629225       1 util.go:215] kubelet create events: /api/v1/namespaces/kube-system/events with status code 201, spent 8.635371ms
I0730 06:48:59.629583       1 util.go:232] start proxying: patch /api/v1/namespaces/kube-system/events/yurthub-n137.16967ecc77c97cc0, in flight requests: 25
I0730 06:48:59.641040       1 util.go:215] kubelet patch events: /api/v1/namespaces/kube-system/events/yurthub-n137.16967ecc77c97cc0 with status code 200, spent 11.420666ms
I0730 06:48:59.641265       1 util.go:232] start proxying: post /api/v1/namespaces/kube-system/events, in flight requests: 25
I0730 06:48:59.649760       1 util.go:215] kubelet create events: /api/v1/namespaces/kube-system/events with status code 201, spent 8.47306ms
I0730 06:48:59.650140       1 util.go:232] start proxying: post /api/v1/namespaces/kube-system/events, in flight requests: 25
I0730 06:48:59.658743       1 util.go:215] kubelet create events: /api/v1/namespaces/kube-system/events with status code 201, spent 8.573537ms
I0730 06:49:05.446525       1 util.go:232] start proxying: put /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s, in flight requests: 25
I0730 06:49:05.446633       1 util.go:215] kubelet update leases: /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s with status code 200, spent 57.32µs
I0730 06:49:15.447450       1 util.go:232] start proxying: put /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s, in flight requests: 25
I0730 06:49:15.447566       1 util.go:215] kubelet update leases: /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s with status code 200, spent 65.556µs
I0730 06:49:25.448337       1 util.go:232] start proxying: put /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s, in flight requests: 25
I0730 06:49:25.448449       1 util.go:215] kubelet update leases: /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s with status code 200, spent 62.788µs
I0730 06:49:35.449228       1 util.go:232] start proxying: put /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s, in flight requests: 25
I0730 06:49:35.449360       1 util.go:215] kubelet update leases: /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s with status code 200, spent 82.644µs
I0730 06:49:45.450147       1 util.go:232] start proxying: put /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s, in flight requests: 25
I0730 06:49:45.450255       1 util.go:215] kubelet update leases: /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s with status code 200, spent 56.962µs
I0730 06:49:55.451017       1 util.go:232] start proxying: put /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s, in flight requests: 25
I0730 06:49:55.451138       1 util.go:215] kubelet update leases: /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s with status code 200, spent 69.817µs
I0730 06:50:05.451857       1 util.go:232] start proxying: put /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s, in flight requests: 25
I0730 06:50:05.451992       1 util.go:215] kubelet update leases: /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s with status code 200, spent 75.143µs
I0730 06:50:15.452792       1 util.go:232] start proxying: put /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s, in flight requests: 25
I0730 06:50:15.452928       1 util.go:215] kubelet update leases: /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/n137?timeout=10s with status code 200, spent 79.432µs
I0730 06:50:22.022691       1 util.go:232] start proxying: post /apis/authorization.k8s.io/v1/subjectaccessreviews, in flight requests: 25
I0730 06:50:22.028287       1 util.go:215] kubelet create subjectaccessreviews: /apis/authorization.k8s.io/v1/subjectaccessreviews with status code 201, spent 5.543403ms
```
