### PR TITLE
Yurtctl modify  kube-controllersetting to close the nodelifecycle-controller

### LINKED ISSUE #391: [BUG]How `yurtctl convert` can better close the `nodelifecycle controller` (`kube-controller-manager`)?
**What happened**:
When excuting the command `yurtctl convert`,  the clusterrolebinding `system:controller:node-controller` will be deleted to turn off the `nodelifecycle controller` (in `kube-controller-manager`).
However, the flowing questions will appear afterwards:
- Other controllers using clusterrolebinding `system:controller:node-controller` can't work normally.
  eg: issue: https://github.com/openyurtio/openyurt/issues/380
- In a high availability scenario, when kube-controller-manager changes the leader, kube-controller-manager can't start successfully because of lack of clusterrolebinding `system:controller:node-controller` .
  Issue: https://github.com/openyurtio/openyurt/issues/347

**What you expected to happen**:
`yurtctl convert`  doesn't  turn off `nodelifecycle controller` by deleting clusterrolebinding `system:controller:node-controller`. And it can support the high availability of `kube-controller-manager`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
*Solutions currently proposed:*
When executing `yurtctl convert`, 1) If `kube-controller-manager` is deployed through static file `/etc/kubernetes/manifests/kube-controller-manager.yaml`: Create jobs for all candidates to modify this file to turn off `nodelifecycle controller` . 2) If `kube-controller-manager` is not deployed through a static file: Modify `kube-controller-manager` template directly.
*And this scheme has the following problems:*
If the kube-controller-manager is not deployed through a static file (/etc/kubernetes/manifests/), modify `kube-controller-manager` template directly will lead to the runtime template is inconsistent with the user's local yaml file.

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind bug

### PR DESCRIPTION
**Pull request by Peeknut**
/kind bug

#### What this PR does / why we need it:
If kube-controlller-manager is deployed as a static pod, `yurtctl convert` turn off `nodelifecycle controller` by modifying `kube-controller-manager.yaml` instead of deleting clusterrolebinding `system:controller:node-controller`. So OpenYurt cluster created by yurtctl can run normally and support the high availability of `kube-controller-manager`.

#### Which issue(s) this PR fixes:

Fixes #391

#### Special notes for your reviewer:

/assign @rambohe-ch

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/yurtctl/constants/constants.go [hunk 1]
```diff
@@ -251,5 +251,57 @@ spec:
...
+      nodeName: {{.nodeName}}
+      containers:
+      - name: yurtctl-enable-node-controller
+        image: {{.yurtctl_servant_image}}
+        imagePullPolicy: IfNotPresent
+        command:
+        - /bin/sh
+        - -c
+        args:
+        - "nsenter -t 1 -m -u -n -i -- sed -i 's/--controllers=-nodelifecycle,/--controllers=/g' {{.pod_manifest_path}}/kube-controller-manager.yaml"
```
Comment (rambohe-ch) [inline pkg/yurtctl/constants/constants.go:303]: if no `--controllers` parameter is set in `kube-controller-manager.yaml`, the above command can not disable `nodelifecycle` controller.

File: pkg/yurtctl/cmd/revert/revert.go [hunk 2]
```diff
@@ -213,30 +219,18 @@ func (ro *RevertOptions) RunRevert() (err error) {
...
-			{
-				Kind:      "ServiceAccount",
-				Name:      "node-controller",
-				Namespace: "kube-system",
-			},
+	// 6. enable node-controller
+	if err = kubeutil.RunServantJobs(ro.clientSet,
+		map[string]string{
+			"action":                "enable",
+			"yurtctl_servant_image": ro.YurtctlServantImage,
```
Comment (rambohe-ch) [inline pkg/yurtctl/cmd/revert/revert.go:226]: why use `ro.YurtctlServantImage` to enable or disable nodelifecycle controller?

File: pkg/yurtctl/constants/constants.go (hunk 1 above)
Comment (Peeknut) [reply pkg/yurtctl/constants/constants.go:303]: Oh, yes. In the cluster installed by kubeadm, the static file of kube-controller-manager contains this parameter `--controllers` by default. In order to deal with other situations, the situation without this parameter should indeed be considered.
And the method of modifying files will be optimized in the future to make string matching more accurate instead of using `sed`.

File: pkg/yurtctl/cmd/revert/revert.go (hunk 2 above)
Comment (Peeknut) [reply pkg/yurtctl/cmd/revert/revert.go:226]: Because the system architecture may be amd64, arm64, arm, using a unified basic image may cause problems. So the parameter of yurtctl convert --yurtctl-servant-image is reused here.
The yurtctl-servant image may be separated from yurtctl in the future for more elegant use.
